### ISSUE TITLE
Purpur1.19.2无法使用

### ISSUE THREAD

**Issue by Chaostarts** [lRENyaaa/Anti-Villager-Lag#1]
22:07:32 ERROR]: Error occurred while enabling VillagerOptimiser v1.3 (Is it up to date?)
>java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.froobworld.avl.utils.ActivityUtils.CURRENT_ACTIVITY_METHOD" is null
at com.froobworld.avl.utils.ActivityUtils.wouldBeBadActivity(ActivityUtils.java:146) ~[VillagerOptimiser-1.3.jar:?]
at com.froobworld.avl.tasks.NormalActivityTask.run(NormalActivityTask.java:15) ~[VillagerOptimiser-1.3.jar:?]
at com.froobworld.avl.tasks.MainTask.run(MainTask.java:24) ~[VillagerOptimiser-1.3.jar:?]
at com.froobworld.avl.tasks.MainTask.<init>(MainTask.java:19) ~[VillagerOptimiser-1.3.jar:?]
at com.froobworld.avl.Avl.startTasks(Avl.java:40) ~[VillagerOptimiser-1.3.jar:?]
at com.froobworld.avl.Avl.onEnable(Avl.java:26) ~[VillagerOptimiser-1.3.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:309) ~[PlugManX.jar:?]
at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:120) ~[PlugManX.jar:?]
at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugManX.jar:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1857]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:925) ~[purpur-1.19.2.jar:git-Purpur-1857]
at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:540) ~[purpur-1.19.2.jar:git-Purpur-1857]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.19.2.jar:git-Purpur-1857]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1857]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1857]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1857]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:07:32 INFO]: [VillagerOptimiser] Disabling VillagerOptimiser v1.3

**Comment by lRENyaaa** [comment]
有空修,现在我忙着给我自己服务端更新1.19.3
